### ISSUE TITLE
Bug in OperationDefinition - print package

### ISSUE THREAD

**Issue by vitalikda** [thomasheyenbrock/graphql-modular#2]
A minor bug in pint package:

Not sure why these check are required:  https://github.com/thomasheyenbrock/graphql-modular/blob/main/packages/print/src/print.ts#L540

But in case when operation does not have name, print removes `query`/`mutation` with beforehand comments. In case of mutation, it also makes it inexecutable. E.g. 

Before print
```gql
# Comment line
mutation { 
  todoCreate(text: "Foo bar") {
    todo {
      id
    }
  }
}
``` 
After print
```gql
{ 
  todoCreate(text: "Foo bar") {
    todo {
      id
    }
  }
}
```

**Comment by thomasheyenbrock** [comment]
Good catch! I just pushed a commit that fixes this: https://github.com/thomasheyenbrock/graphql-modular/commit/50f7f80de7898caf114a02000f44141fa152de53

**Comment by thomasheyenbrock** [comment]
I published another commit that also takes care of the query shorthand properly: https://github.com/thomasheyenbrock/graphql-modular/commit/e03cd0d3375e28ab83f48d7eebc93471bd53f024
- A query shorthand is now parsed as `SelectionSet` and not as `OperationDefinition`
- That allows the printer to differentiate between the two cases  `{ id }` (just a selection set in the AST) and `query { id }` (a operation definition in the AST)
